# Created by Eyal Levy
# eyal@levys.co.il
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  generation: 4
  name: demo1
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}
